# Generated by Django 6.0.5 on 2026-06-10 04:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_assessmentsubmission'),
        ('courses', '0003_courseenrollment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_assessments', to='courses.course'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='is_onboarding',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assessmentsubmission',
            name='skill_scores',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='question',
            name='skill_tag',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='courses.module'),
        ),
        migrations.AlterUniqueTogether(
            name='assessmentsubmission',
            unique_together={('user', 'assessment')},
        ),
    ]
