# Generated by Django 6.0.5 on 2026-06-13 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_subtopic'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='intro_content',
            field=models.TextField(blank=True, default=''),
        ),
    ]
